### ISSUE TITLE
Про имя пользователя на GitHub 

### ISSUE THREAD

**Issue by vkats-spbu** [Gleb-Shall/problem-1#1]
Просьба изменить имя пользователя на GitHub на легко ассоциируемое с Вами, как Вам было указано в рекомендациях по подготовке к занятиям. См. [https://docs.github.com/ru/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username#changing-your-username](url)

**Comment by bymyshegibar** [comment]
Я указал на аккаунте имя Gleb_shal, нужно изменить на что то более
ассоциируемое?

пн, 23 сент. 2024 г., 17:51 vkats-spbu ***@***.***>:

**Comment by vkats-spbu** [comment]
Так намного лучше
